name: Author-Tagger
description: Adds a label based on user who opened a pull request
inputs:
  token:
    description: access token
    required: false
    default: ${{ github.token }}
branding:
  icon: plus-square
  color: green
runs:
  using: node12
  main: dist/index.js
